export const STORAGE_KEYS = {
  APP_STATE: 'builderprep.appState.v1',
  QUESTION_BANK: 'builderprep.questionBank.v1'
};

export const DEFAULT_APP_STATE = {
  route: 'dashboard',
  theme: 'dark',
  language: 'en',
  user: {
    id: 'local-user-1',
    name: 'Local Student',
    email: ''
  },
  preferences: {
    selectedLicenseId: 'va-a1',
    dailyGoalMinutes: 20,
    examLength: 10,
    examMinutes: 20
  },
  studyFilters: {
    licenseId: 'all',
    topic: 'all',
    difficulty: 'all',
    search: '',
    onlyFavorites: false,
    onlyIncorrect: false,
    onlyReviewLater: false,
    randomized: false
  },
  favorites: [],
  reviewLater: [],
  mastery: {},
  questionStats: {},
  sessionHistory: [],
  achievements: [],
  studySession: {
    questionIds: [],
    currentIndex: 0,
    revealAnswer: false,
    selectedAnswerId: null,
    lastGeneratedAt: null
  },
  examSession: {
    active: false,
    questionIds: [],
    currentIndex: 0,
    answers: {},
    startedAt: null,
    durationMinutes: 20,
    results: null,
    selectedLicenseId: 'va-a1'
  }
};

export const DIFFICULTY_ORDER = ['easy', 'medium', 'hard'];

export const UI_TEXT = {
  en: {
    language: 'Language',
    darkMode: 'Dark mode',
    installApp: 'Install app',
    dashboard: 'Dashboard',
    studyMode: 'Study mode',
    examMode: 'Exam mode',
    reviewCenter: 'Review center',
    progress: 'Progress',
    adminPanel: 'Admin panel',
    settings: 'Settings',
    offlineReady: 'Offline ready',
    syncStatus: 'Sync status',
    syncDescription: 'This starter works fully offline. Cloud endpoints can be wired later.',
    exportBackup: 'Export backup',
    importBackup: 'Import backup',
    totalQuestions: 'Total questions',
    accuracy: 'Accuracy',
    studySessions: 'Study sessions',
    currentStreak: 'Current streak',
    quickActions: 'Quick actions',
    continueStudy: 'Continue study',
    startExam: 'Start exam',
    smartReview: 'Smart review',
    weakTopics: 'Weak topics',
    recentActivity: 'Recent activity',
    recommendedQueue: 'Recommended queue',
    noWeakTopics: 'No weak topics yet. Answer more questions to see patterns.',
    noHistory: 'No session history yet. Start studying or launch an exam.',
    studyControls: 'Study controls',
    license: 'License',
    topic: 'Topic',
    difficulty: 'Difficulty',
    search: 'Search',
    favoritesOnly: 'Favorites only',
    incorrectOnly: 'Incorrect only',
    reviewLaterOnly: 'Review later only',
    randomized: 'Randomized',
    generateSet: 'Generate set',
    previous: 'Previous',
    next: 'Next',
    revealAnswer: 'Reveal answer',
    hideAnswer: 'Hide answer',
    favorite: 'Favorite',
    unfavorite: 'Unfavorite',
    markReviewLater: 'Review later',
    removeReviewLater: 'Remove review later',
    markMastered: 'Mark mastered',
    markNeedsWork: 'Mark needs work',
    explanation: 'Explanation',
    examSetup: 'Exam setup',
    questionCount: 'Question count',
    durationMinutes: 'Duration (minutes)',
    startExamNow: 'Start exam now',
    submitExam: 'Submit exam',
    finishAttempt: 'Finish attempt',
    timeRemaining: 'Time remaining',
    questionNumber: 'Question',
    answered: 'Answered',
    unanswered: 'Unanswered',
    passed: 'Passed',
    failed: 'Failed',
    score: 'Score',
    correct: 'Correct',
    incorrect: 'Incorrect',
    reviewAnswers: 'Review answers',
    weakQuestionQueue: 'Weak question queue',
    favoritesReview: 'Favorites review',
    mistakesTable: 'Most missed questions',
    emptyFavorites: 'No favorites yet.',
    emptyMistakes: 'No missed questions yet.',
    adminOverview: 'Admin overview',
    importQuestions: 'Import questions',
    exportQuestions: 'Export questions',
    addQuestion: 'Add question',
    saveQuestion: 'Save question',
    resetProgress: 'Reset progress',
    profile: 'Profile',
    displayName: 'Display name',
    email: 'Email',
    saveProfile: 'Save profile',
    dailyGoalMinutes: 'Daily goal (minutes)',
    saveSettings: 'Save settings',
    theme: 'Theme',
    questionTextEnglish: 'Question text (English)',
    questionTextSpanish: 'Question text (Español)',
    answerA: 'Answer A',
    answerB: 'Answer B',
    answerC: 'Answer C',
    answerD: 'Answer D',
    explanationEnglish: 'Explanation (English)',
    explanationSpanish: 'Explanation (Español)',
    correctAnswer: 'Correct answer',
    category: 'Category',
    tags: 'Tags',
    topicPerformance: 'Topic performance',
    usageByLicense: 'Usage by license',
    achievements: 'Achievements',
    localCloudReady: 'Local now, cloud-ready later',
    installHint: 'Installable PWA shell, offline cache, local profile, import/export, and modular data model are included in this starter.',
    clearExam: 'Clear exam',
    activeExam: 'Active exam',
    noQuestionsMatch: 'No questions match the current filters.',
    smartExplanation: 'Smart review prioritizes missed questions, low mastery, and older items.',
    imported: 'Imported successfully.',
    saved: 'Saved successfully.',
    resetDone: 'Progress reset completed.',
    backupLoaded: 'Backup imported successfully.',
    backupSaved: 'Backup exported successfully.',
    yes: 'Yes',
    no: 'No'
  },
  es: {
    language: 'Idioma',
    darkMode: 'Modo oscuro',
    installApp: 'Instalar app',
    dashboard: 'Panel',
    studyMode: 'Modo estudio',
    examMode: 'Modo examen',
    reviewCenter: 'Centro de repaso',
    progress: 'Progreso',
    adminPanel: 'Panel admin',
    settings: 'Configuración',
    offlineReady: 'Listo sin conexión',
    syncStatus: 'Estado de sincronización',
    syncDescription: 'Esta base funciona completamente offline. Luego puedes conectar endpoints en la nube.',
    exportBackup: 'Exportar respaldo',
    importBackup: 'Importar respaldo',
    totalQuestions: 'Preguntas totales',
    accuracy: 'Precisión',
    studySessions: 'Sesiones de estudio',
    currentStreak: 'Racha actual',
    quickActions: 'Acciones rápidas',
    continueStudy: 'Continuar estudio',
    startExam: 'Iniciar examen',
    smartReview: 'Repaso inteligente',
    weakTopics: 'Temas débiles',
    recentActivity: 'Actividad reciente',
    recommendedQueue: 'Cola recomendada',
    noWeakTopics: 'Aún no hay temas débiles. Responde más preguntas para ver patrones.',
    noHistory: 'Todavía no hay historial. Empieza a estudiar o lanza un examen.',
    studyControls: 'Controles de estudio',
    license: 'Licencia',
    topic: 'Tema',
    difficulty: 'Dificultad',
    search: 'Buscar',
    favoritesOnly: 'Solo favoritas',
    incorrectOnly: 'Solo incorrectas',
    reviewLaterOnly: 'Solo repasar luego',
    randomized: 'Aleatorio',
    generateSet: 'Generar set',
    previous: 'Anterior',
    next: 'Siguiente',
    revealAnswer: 'Mostrar respuesta',
    hideAnswer: 'Ocultar respuesta',
    favorite: 'Favorita',
    unfavorite: 'Quitar favorita',
    markReviewLater: 'Repasar luego',
    removeReviewLater: 'Quitar de repasar luego',
    markMastered: 'Marcar dominada',
    markNeedsWork: 'Marcar necesita trabajo',
    explanation: 'Explicación',
    examSetup: 'Configuración del examen',
    questionCount: 'Cantidad de preguntas',
    durationMinutes: 'Duración (minutos)',
    startExamNow: 'Iniciar examen ahora',
    submitExam: 'Enviar examen',
    finishAttempt: 'Finalizar intento',
    timeRemaining: 'Tiempo restante',
    questionNumber: 'Pregunta',
    answered: 'Respondidas',
    unanswered: 'Sin responder',
    passed: 'Aprobado',
    failed: 'Reprobado',
    score: 'Puntaje',
    correct: 'Correctas',
    incorrect: 'Incorrectas',
    reviewAnswers: 'Revisar respuestas',
    weakQuestionQueue: 'Cola de preguntas débiles',
    favoritesReview: 'Repaso de favoritas',
    mistakesTable: 'Preguntas más falladas',
    emptyFavorites: 'Todavía no hay favoritas.',
    emptyMistakes: 'Todavía no hay preguntas falladas.',
    adminOverview: 'Resumen admin',
    importQuestions: 'Importar preguntas',
    exportQuestions: 'Exportar preguntas',
    addQuestion: 'Agregar pregunta',
    saveQuestion: 'Guardar pregunta',
    resetProgress: 'Reiniciar progreso',
    profile: 'Perfil',
    displayName: 'Nombre visible',
    email: 'Correo',
    saveProfile: 'Guardar perfil',
    dailyGoalMinutes: 'Meta diaria (minutos)',
    saveSettings: 'Guardar configuración',
    theme: 'Tema',
    questionTextEnglish: 'Texto de la pregunta (English)',
    questionTextSpanish: 'Texto de la pregunta (Español)',
    answerA: 'Respuesta A',
    answerB: 'Respuesta B',
    answerC: 'Respuesta C',
    answerD: 'Respuesta D',
    explanationEnglish: 'Explicación (English)',
    explanationSpanish: 'Explicación (Español)',
    correctAnswer: 'Respuesta correcta',
    category: 'Categoría',
    tags: 'Etiquetas',
    topicPerformance: 'Rendimiento por tema',
    usageByLicense: 'Uso por licencia',
    achievements: 'Logros',
    localCloudReady: 'Local ahora, listo para nube después',
    installHint: 'Esta base ya incluye shell PWA instalable, caché offline, perfil local, importación/exportación y modelo de datos modular.',
    clearExam: 'Limpiar examen',
    activeExam: 'Examen activo',
    noQuestionsMatch: 'No hay preguntas que coincidan con los filtros actuales.',
    smartExplanation: 'El repaso inteligente prioriza preguntas falladas, baja dominación y preguntas antiguas.',
    imported: 'Importado correctamente.',
    saved: 'Guardado correctamente.',
    resetDone: 'El progreso fue reiniciado.',
    backupLoaded: 'Respaldo importado correctamente.',
    backupSaved: 'Respaldo exportado correctamente.',
    yes: 'Sí',
    no: 'No'
  }
};
